name: Build

on: push

jobs:
  build:
    name: text2speech build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: ConorMacBride/install-package@v1
        with:
          apt: libasound2-dev libc6-dev-i386

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          cache: true
          go-version: "1.24"

      - name: Prepare
        run: |
          go clean -r ./...
          go mod tidy

      - name: Test
        run: |
          go test -v -race -count 1 -parallel 50 -covermode=atomic -coverprofile="coverage.out" ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true # optional (default = false)

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m

      - name: Build 
        run: |
          make build

      - name: Govulncheck
        uses: kmulvey/govulncheck-action@v1.4.0
