name: text2speech

on: push

jobs:
  build:
    name: text2speech build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: ConorMacBride/install-package@v1
        with:
          apt: libasound2-dev libc6-dev-i386
      
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 
        uses: actions/setup-go@v3
        with:
          check-latest: true
          cache: true
          go-version: 1.19
        id: go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m

      - name: Govulncheck
        uses: kmulvey/govulncheck-action@v1.0.0

      - name: Build & Test
        run: |
          go mod tidy
          go test -v -race -count 1 ./...
          go build -v -ldflags="-s -w" ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3  
        with:
          verbose: true # optional (default = false)

  release:
    name: text2speech release
    runs-on: ubuntu-latest

    steps:
      - uses: ConorMacBride/install-package@v1
        with:
          apt: libasound2-dev libc6-dev-i386
      
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go 
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --config .goreleaser.yaml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
